name: Publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    steps:
      - name: "📥 Checkout repository"
        uses: actions/checkout@v6
      - name: "☕️ Setup JDK"
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: ${{ matrix.java }}
      - name: "🐘 Setup Gradle"
        uses: gradle/actions/setup-gradle@748248ddd2a24f49513d8f472f81c3a07d4d50e1 # v4.4.4
        with:
          develocity-access-key: ${{ secrets.GRAILS_DEVELOCITY_ACCESS_KEY  }}
      - name: Publish Grails Forge UI
        run: ./publish.sh
        env:
          GITHUB_SLUG: grails/grails-forge-ui
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}